version: "3.9"

services:
  fastapi:
    build:
      context: .                      # repo root
      dockerfile: code/deployment/api/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn code.deployment.api.main:app --host 0.0.0.0 --port 8000 --reload

  streamlit:
    build:
      context: .
      dockerfile: code/deployment/app/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - DIGIT_API_URL=http://fastapi:8000/predict  # Add this line
    command: streamlit run code/deployment/app/app.py --server.port=8501 --server.address=0.0.0.0

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    environment:
      - MLFLOW_TRACKING_URI=/mlruns
    volumes:
      - ./mlruns:/mlruns
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri /mlruns --host 0.0.0.0 --port 5000
